<a href="https://colab.research.google.com/github/fafa20252025/fariba/blob/main/first_ml_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [90]:
data=pd.read_csv("Boston.csv")

In [91]:
data.head() #print top 5 rows of the data for a quick inspection

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [92]:
data.shape #print the toal numbers of rows and columns .. med is output column and the rest are input column.

(506, 15)

In [93]:
data.dtypes

Unnamed: 0      int64
crim          float64
zn            float64
indus         float64
chas            int64
nox           float64
rm            float64
age           float64
dis           float64
rad             int64
tax             int64
ptratio       float64
black         float64
lstat         float64
medv          float64
dtype: object

In [94]:
data.isnull().sum()

Unnamed: 0    0
crim          0
zn            0
indus         0
chas          0
nox           0
rm            0
age           0
dis           0
rad           0
tax           0
ptratio       0
black         0
lstat         0
medv          0
dtype: int64

In [95]:
data.duplicated().sum()

np.int64(0)

In [96]:
data.drop_duplicates(inplace=True)

# **check and remove ouliers**

outliners are datapoints which are very far from best fit line. these outliners will affect the best fit line.

In [97]:
def remove_outliers(data, column):
  for column in column:
    if column in data.columns:
      Q1=data[column].quantile(0.25)
      Q3=data[column].quantile(0.75)
      iqr=Q3-Q1
      lower_bound=Q1-1.5*iqr
      upper_bound=Q3+1.5*iqr
      data=data[(data[column]>=lower_bound) & (data[column]<=upper_bound)]
  return data

In [98]:
data_without_outliers=remove_outliers(data,data.columns)

In [99]:
data.shape  #original data

(506, 15)

In [100]:
data_without_outliers.shape #when running outliers function, the whole row will be dropped.

(214, 15)

# **machine learning process**

1- split data inot training and testing

In [101]:
x_train,x_test,y_train,y_test=train_test_split(data.drop("medv",axis=1),data["medv"],test_size=0.2,random_state=42)

2- apply linear regression on the training data

In [102]:
lin_reg=LinearRegression() # lin_reg is an object of class LinearRegression
lin_reg.fit(x_train,y_train) #best fit line willl be stored in object (lin_reg)

LinearRegression()

In [103]:
lin_reg = LinearRegression() #it shows from m1 to m13
lin_reg.fit(x_train, y_train) #.fit() is a fuction.
lin_reg.coef_

array([-3.47490827e-03, -1.13313604e-01,  3.23067056e-02,  4.35516844e-02,
        2.75621916e+00, -1.69386529e+01,  4.48663161e+00, -1.09175430e-02,
       -1.47608119e+00,  2.92666304e-01, -9.92202267e-03, -9.11544575e-01,
        1.24202332e-02, -5.12262693e-01])

In [104]:
lin_reg.intercept_ #it shows C value

np.float64(30.412686521180213)

self.coef_ and self.intercept_ are LineraRegression class variables.

In [105]:
y_pred=lin_reg.predict(x_test) #store the predicted value in y_pred variable

compare the predicted values to the test value for y_test

In [106]:
y_pred=lin_reg.predict(x_test) #store the predicted value in y_pred variable
pd.DataFrame({"Actual":y_test,"Predicted":y_pred})

#Actual is y_test value and the second one is predicted value for y. 102 rows for test has been done on y
#y_test and y_pred are two arrays are made to dictionary and convertin the dictionary into a dataframe.

     Actual  Predicted
173    23.6  28.973354
274    32.4  35.877958
491    13.6  13.973662
72     22.8  25.615840
452    16.1  18.666082
..      ...        ...
412    17.9  -0.345555
436     9.6  13.625095
411    17.2  16.153675
86     22.5  22.548659
75     21.4  25.008526

[102 rows x 2 columns]

calcualte the accuracy of the prediction

In [107]:
r2_score(y_test,y_pred) #0.66 or 66% is the accuracy of our model.

0.6659408703343057